length_buckets:
  short:    {k: 0.24, gamma_exit: 0.90, gamma_boost: 0.20, eps: 0.10, beta: 0.30}
  medium:   {k: 0.08, gamma_exit: 0.48, gamma_boost: 0.20, eps: 0.08, beta: 0.40}
  long:     {k: 0.06, gamma_exit: 0.40, gamma_boost: 0.25, eps: 0.05, beta: 0.50}

alpha_rule: "min(3.0, 1 + N / 10)"

input_type_scores:
  check_box: 1
  radio_button: 1
  dropdown: 2
  media_selector: 2
  slider: 3
  date_picker: 3
  text_input_short: 3
  search_input: 4
  text_input_long: 4

traffic_source_multipliers:
  paid_search:    1.3
  paid_social:    1.1
  organic_search: 1.0
  direct_referral:1.0
  display_email:  0.9
  social_organic: 0.7

weights:
  w_E: 0.6
  w_N: 0.4
  w_c: 1.0
  w_cb: 0.8
  w_f: 1.2